name: Scheduler Data Update

on:
  schedule:
    - cron: "23 23 * * *"
  workflow_dispatch:

env:
  TZ: "Asia/Jakarta"
  PYTHONBUFFERED: 1

jobs:
  update:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current time
        run: date

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.23"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python duplicate_test.py