name: Scheduler Data Update

on:
  schedule:
    - cron: "23 23 * * *"
  workflow_dispatch:

env:
  TZ: "Asia/Jakarta"
  PYTHONBUFFERED: 1

jobs:
  update:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current time
        run: date

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.23"

      - name: Install dependencies
        run: |
          pip install -r requirement.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1012485468217/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gspread-access-10@kerjaan-pribadi.iam.gserviceaccount.com"
          export_default_credentials: true

      - name: Run script
        run: python duplicate_test.py